//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKATEGORILER
    {
        public short KATEGORIID { get; set; }

        [Required(ErrorMessage ="Please enter the CATEGORY NAME!s")] 
        // özelliðin gerekli bir alan olduðunu belirtir. Add Category kýsmýnda ad kýsmýný boþ geçersek hata almamýzý saðlar.
        //Uyarý vererek kullanýcýyý bilgilendirebiliriz.
        public string KATEGORIAD { get; set; }
        public TBLURUNLER TBLURUNLER { get; set; }

        
    }
}
